import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { NextRequest } from 'next/server';
import { GET, POST } from '../src/app/api/draw/[...action]/route';
import { getStore } from '../src/lib/store';
test('API boundary: CSRF, session cookie, authorization, duplicate draw, early result/export/backup protection',async()=>{
  const dir=await mkdtemp(join(tmpdir(),'ictc-api-'));process.env.DRAW_DATA_FILE=join(dir,'event.json');process.env.APP_MODE='demo';process.env.DATA_DRIVER='file';
  let cookie='';
  const call=(name:string,body:unknown,origin='http://localhost:3100')=>POST(new NextRequest(`http://localhost:3100/api/draw/${name}`,{method:'POST',headers:{origin,'content-type':'application/json',cookie},body:JSON.stringify(body)}),{params:Promise.resolve({action:[name]})});
  const read=(name:string)=>GET(new NextRequest(`http://localhost:3100/api/draw/${name}`,{headers:{cookie}}),{params:Promise.resolve({action:[name]})});
  assert.equal((await call('draw',{requestId:randomUUID(),prizeId:'prize-01',count:1})).status,401);
  assert.equal((await call('login',{code:'ICTC-DEMO'},'https://attacker.invalid')).status,403);
  assert.equal((await read('backup')).status,401);
  const auth=await call('login',{code:'ICTC-DEMO'});assert.equal(auth.status,200);
  const header=auth.headers.get('set-cookie')!;assert.match(header,/HttpOnly/i);assert.match(header,/SameSite=strict/i);cookie=header.split(';')[0];
  const body={requestId:randomUUID(),prizeId:'prize-01',count:1};
  const first=await (await call('draw',body)).json();const second=await (await call('draw',body)).json();assert.equal(first.roundId,second.roundId);
  const snap=await (await read('state')).json();assert.equal(snap.active.winners.length,0);assert.equal(snap.history.length,0);assert.equal(snap.role,'admin');
  assert.equal((await read('backup')).status,409);const exported=await (await read('export')).text();assert.equal(exported.split('\r\n').length,1);
  const store=await getStore();await store.transaction(s=>{s.rounds[0].createdAt=Date.now()-5000;s.rounds[0].revealAt=Date.now()-2000;});
  const shown=await read('state');assert.match(shown.headers.get('cache-control')!,/no-store/);assert.equal((await shown.json()).active.winners.length,1);
  const backup=await (await read('backup')).json();assert.equal(backup.codes,undefined);assert.equal(backup.sessions,undefined);
  await call('logout',{});assert.equal((await read('export')).status,401);
  delete process.env.DRAW_DATA_FILE;
});
